tests: Add tests for various error flows
linux-rdma/rdma-core pull request #1117
Opened 2022-01-03 14:01 UTC by firasj

This series adds various error flow tests on post send/receive operations, and adds instances of these tests for UD and SRD.

2022-01-04 13:07 UTC, EdwardSro requested changes

2022-01-04 13:07 UTC, EdwardSro commented on tests/test_efa_srd.py
> +    def full_sq_bad_flow(self):
Is there a reason why you chose to skip UD in this case?

2022-01-17 13:02 UTC, jgunthorpe requested changes
Address Edward's remarks

2022-01-19 14:06 UTC, firasj reviewed
Sorry for the delay.
I have addressed all of your comments and updated the commits.

2022-01-19 14:08 UTC, firasj commented on tests/utils.py
> +    with unittest.TestCase().assertRaises(PyverbsRDMAError) as ex:
Replaced `traffic_obj` with `test_obj`, an instance of `RDMATestCase`.

2022-02-01 10:12 UTC, EdwardSro approved these changes

2022-02-08 12:11 UTC, firasj commented
Kind reminder.

2022-02-08 12:14 UTC, rleon commented
Thanks for the reminder

2022-02-08 12:14 UTC, merged