[PATCH rdma-core 00/10] libhns: Support cqe inline, handle rq inline compatibility, fix sge num bug
linux-rdma/rdma-core pull request #1240
Opened 2022-10-25 11:24 UTC by haoyue-Xu

The patchset mainly fixes and refactors the code relate to inline
features and supports cqe inline in user space.
1.#1-4: Fix the problem of sge
2.#5-8: rq inline related patches(handle compatibility, refactor
rq inline, add new interface to support rq inline)
3.#9-10: support cqe inline

The kernal space part is named "RDMA/hns:
Fix sge_num bug and refactor rq inline, add cqe inline".
https://patchwork.kernel.org/project/linux-rdma/list/?series=688632

Luoyouming (10):
libhns: Use a constant instead of sizeof operation
libhns: Fix ext_sge num error when post send
Update kernel headers
libhns: Fix the problem of sge nums
Update kernel headers
libhns: Add compatibility handling for rq inline
libhns: Refactor rq inline
libhns: RQ inline support wc_x_poll_cq interface
Update kernel headers
libhns: Support cqe inline

kernel-headers/rdma/hns-abi.h    |  19 ++++
providers/hns/hns_roce_u.c       |  10 +-
providers/hns/hns_roce_u.h       |  29 +++---
providers/hns/hns_roce_u_abi.h   |   2 +-
providers/hns/hns_roce_u_hw_v2.c | 152 ++++++++++++++++++------------
providers/hns/hns_roce_u_hw_v2.h |   4 +-
providers/hns/hns_roce_u_verbs.c | 157 ++++++++++++++++++++++---------
7 files changed, 252 insertions(+), 121 deletions(-)

-- 
2.30.0

2022-11-21 18:28 UTC, jgunthorpe requested changes

2022-12-09 08:17 UTC, haoyue-Xu commented on kernel-headers/rdma/hns-abi.h
Yes, I need to upload the kernel patch first. I will resend this patch set. Thank you.

2023-02-27 03:58 UTC, haoyue-Xu commented
I resend this patch set, and the kernel patches have merged.

2023-03-22 15:17 UTC, jgunthorpe commented
/azp run

2023-03-22 17:37 UTC, merged