pyverbs: Add support for null memory regions.
linux-rdma/rdma-core pull request #965
Opened 2021-03-20 14:55 UTC by TaranovK

The patch adds support for null MRs for pyverbs as well as for rdmacm.
The patch also adds man pages for rdmacm.

2021-03-22 07:46 UTC, rleon commented
Why do we need it in rdma-cm?

2021-03-22 12:21 UTC, TaranovK commented
> Why do we need it in rdma-cm?

It was a side effect of implementing is_null in pyverbs. Another solution is simply raise an error in pyverb if a client used rdmacm.
To be honest, I never understood why rdmacm implements rdma_reg_* in the first place, and why somebody reused that useless API in pyverbs. 

If you want I can rewrite the commit and remove changes to rdmacm.

2021-03-22 14:01 UTC, rleon commented
> > Why do we need it in rdma-cm?
> 
> It was a side effect of implementing is_null in pyverbs. Another solution is simply raise an error in pyverb if a client used rdmacm.
> To be honest, I never understood why rdmacm implements rdma_reg_* in the first place, and why somebody reused that useless API in pyverbs.
> 
> If you want I can rewrite the commit and remove changes to rdmacm.

I'll leave to @EdwardSro to comment about pyverbs, but regarding rdma-cm, please remove.
We don't want to add API that not in use.

Thanks

2021-03-24 18:51 UTC, EdwardSro requested changes

2021-03-24 18:51 UTC, EdwardSro commented on pyverbs/mr.pyx
> +                self.mr = v.ibv_alloc_null_mr(pd.pd)
why not to add this check at the beginning (right after line 60), and after successfully allocating a null mr you can just return. IMO it'd be more clear.

2021-03-24 18:51 UTC, EdwardSro commented on pyverbs/mr.pyx
> +                self.mr = NULL
I think it's better to just remove this check, and add an explanation to the docstring, something like "Allocate a null memory region (valid only with PD creator)"

2021-03-24 18:58 UTC, EdwardSro commented
> To be honest, I never understood why rdmacm implements rdma_reg_* in the first place, and why somebody reused that useless API in pyverbs.

They were added to Pyverbs as part of other rdmacm APIs coverage and test flows.
But I agree that they're useless...

2021-04-11 09:33 UTC, rleon commented
What is the status of this PR?

Thanks

2021-04-11 10:01 UTC, TaranovK commented
Hi,

Our team decided not to continue working on this issue, as we fully switched to C/C++ in our project.  

Best,
Konstantin

2021-04-11 10:01 UTC, closed without merging